spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/openfeign
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
server:
  port: 8083